FROM mcr.microsoft.com/dotnet/nightly/sdk:10.0 AS build
WORKDIR /src
COPY src ./src
RUN dotnet restore src/Backend/Backend.csproj
RUN dotnet publish src/Backend/Backend.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/nightly/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "Magalcom.Crm.Backend.dll"]
