CREATE TABLE [crm].[Project]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Project_Id] DEFAULT (NEWSEQUENTIALID()),
    [Name] NVARCHAR(200) NOT NULL,
    [Department] NVARCHAR(100) NOT NULL,
    [Domain] NVARCHAR(100) NOT NULL,
    [IsActive] BIT NOT NULL CONSTRAINT [DF_Project_IsActive] DEFAULT ((1)),
    [CreatedAtUtc] DATETIME2(0) NOT NULL CONSTRAINT [DF_Project_CreatedAtUtc] DEFAULT (SYSUTCDATETIME()),
    [UpdatedAtUtc] DATETIME2(0) NOT NULL CONSTRAINT [DF_Project_UpdatedAtUtc] DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT [PK_Project] PRIMARY KEY CLUSTERED ([Id] ASC)
);

GO
