CREATE TABLE [crm].[Formula]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Formula_Id] DEFAULT (NEWSEQUENTIALID()),
    [Name] NVARCHAR(200) NOT NULL,
    [Expression] NVARCHAR(500) NOT NULL,
    [IsActive] BIT NOT NULL CONSTRAINT [DF_Formula_IsActive] DEFAULT ((1)),
    [CreatedAtUtc] DATETIME2(0) NOT NULL CONSTRAINT [DF_Formula_CreatedAtUtc] DEFAULT (SYSUTCDATETIME()),
    [UpdatedAtUtc] DATETIME2(0) NOT NULL CONSTRAINT [DF_Formula_UpdatedAtUtc] DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT [PK_Formula] PRIMARY KEY CLUSTERED ([Id] ASC)
);

GO
