CREATE TABLE [crm].[WorkType]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_WorkType_Id] DEFAULT (NEWID()),
    [Code] NVARCHAR(50) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
    [SortOrder] INT NOT NULL CONSTRAINT [DF_WorkType_SortOrder] DEFAULT ((0)),
    [IsActive] BIT NOT NULL CONSTRAINT [DF_WorkType_IsActive] DEFAULT ((1)),
    [CreatedAtUtc] DATETIME2(0) NOT NULL CONSTRAINT [DF_WorkType_CreatedAtUtc] DEFAULT (SYSUTCDATETIME()),
    [UpdatedAtUtc] DATETIME2(0) NOT NULL CONSTRAINT [DF_WorkType_UpdatedAtUtc] DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT [PK_WorkType] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_WorkType_Code] UNIQUE NONCLUSTERED ([Code] ASC)
);

GO
