CREATE TABLE [crm].[Customer]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Customer_Id] DEFAULT (NEWID()),
    [Name] NVARCHAR(200) NOT NULL,
    [ExternalId] NVARCHAR(100) NOT NULL,
    [IsActive] BIT NOT NULL CONSTRAINT [DF_Customer_IsActive] DEFAULT ((1)),
    [CreatedAtUtc] DATETIME2(0) NOT NULL CONSTRAINT [DF_Customer_CreatedAtUtc] DEFAULT (SYSUTCDATETIME()),
    [UpdatedAtUtc] DATETIME2(0) NOT NULL CONSTRAINT [DF_Customer_UpdatedAtUtc] DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_Customer_ExternalId] UNIQUE NONCLUSTERED ([ExternalId] ASC)
);

GO
